"""initial schema

Revision ID: 2db789a1eb66
Revises: 
Create Date: 2026-08-27 23:13:51.545771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2db789a1eb66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investors',
    sa.Column('fund_name', sa.String(length=300), nullable=False),
    sa.Column('investor_name', sa.String(length=300), nullable=False),
    sa.Column('investor_type', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('stage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geography', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('portfolio', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_investments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('check_size_min', sa.String(length=50), nullable=False),
    sa.Column('check_size_max', sa.String(length=50), nullable=False),
    sa.Column('partner', sa.String(length=200), nullable=False),
    sa.Column('contact_channel', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='orgrole', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    op.create_table('workspaces',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_workspace_slug')
    )
    op.create_table('ai_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_workspace_id'), 'ai_runs', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('evidence',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('FACT', 'HYPOTHESIS', 'INFERENCE', 'UNKNOWN', name='evidencestatus', native_enum=False, length=20), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_workspace_id'), 'evidence', ['workspace_id'], unique=False)
    op.create_table('integrations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.Enum('SEARCH', 'EMAIL', 'SOCIAL', 'ANALYTICS', 'CRM', 'ENRICHMENT', name='integrationprovidertype', native_enum=False, length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('NOT_CONFIGURED', 'CONNECTED', 'DISCONNECTED', 'ERROR', name='integrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connected_by', sa.Uuid(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_table('products',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('target_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing', sa.String(length=500), nullable=False),
    sa.Column('business_model', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=False),
    sa.Column('key_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta', sa.String(length=500), nullable=False),
    sa.Column('social_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('launch_status', sa.String(length=100), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_workspace_id'), 'products', ['workspace_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.Enum('WEBPAGE', 'RSS', 'ATOM', 'API', 'SITEMAP', 'USER_SUBMITTED', 'OFFICIAL_INTEGRATION', name='researchsourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_workspace_id'), 'research_sources', ['workspace_id'], unique=False)
    op.create_table('actions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('CUSTOMER', 'INVESTOR', 'MARKETING', 'CONTENT', 'COMPETITOR', 'LAUNCH', name='actioncategory', native_enum=False, length=20), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_value_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('TODAY', 'UPCOMING', 'WAITING', 'COMPLETED', 'SNOOZED', name='actionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_product_id'), 'actions', ['product_id'], unique=False)
    op.create_index(op.f('ix_actions_workspace_id'), 'actions', ['workspace_id'], unique=False)
    op.create_table('brand_brain',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('voice', sa.String(length=300), nullable=False),
    sa.Column('tone', sa.String(length=300), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('key_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('words_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('words_to_avoid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proof_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('founder_story', sa.Text(), nullable=False),
    sa.Column('product_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_brain_workspace_id'), 'brand_brain', ['workspace_id'], unique=False)
    op.create_table('brand_mentions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'QUESTION', 'PURCHASE_INTENT', 'COMPETITOR_COMPARISON', 'FEEDBACK', name='mentioncategory', native_enum=False, length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_mentions_product_id'), 'brand_mentions', ['product_id'], unique=False)
    op.create_index(op.f('ix_brand_mentions_workspace_id'), 'brand_mentions', ['workspace_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('audience_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_product_id'), 'campaigns', ['product_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('companies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('employee_estimate', sa.String(length=50), nullable=False),
    sa.Column('funding_stage', sa.String(length=100), nullable=False),
    sa.Column('funding_amount', sa.String(length=100), nullable=False),
    sa.Column('funding_date', sa.Date(), nullable=True),
    sa.Column('technology_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('growth_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('potential_pain', sa.Text(), nullable=False),
    sa.Column('icp_fit_score', sa.Float(), nullable=False),
    sa.Column('icp_fit_category', sa.Enum('EXCELLENT', 'STRONG', 'POTENTIAL', 'LOW_PRIORITY', name='companyfitcategory', native_enum=False, length=20), nullable=False),
    sa.Column('icp_fit_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_score_override', sa.Float(), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Enum('FACT', 'HYPOTHESIS', 'INFERENCE', 'UNKNOWN', name='evidencestatus', native_enum=False, length=20), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('PROSPECT', 'QUALIFIED', 'DRAFTED', 'APPROVED', 'SENT', 'REPLIED', 'MEETING', 'WON', 'LOST', 'NOT_NOW', name='pipelinestage', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_product_id'), 'companies', ['product_id'], unique=False)
    op.create_index(op.f('ix_companies_workspace_id'), 'companies', ['workspace_id'], unique=False)
    op.create_table('competitors',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_content_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_product_id'), 'competitors', ['product_id'], unique=False)
    op.create_index(op.f('ix_competitors_workspace_id'), 'competitors', ['workspace_id'], unique=False)
    op.create_table('content',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'DRAFT', 'APPROVED', 'PUBLISHED', name='contentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_idea_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_idea_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_product_id'), 'content', ['product_id'], unique=False)
    op.create_index(op.f('ix_content_workspace_id'), 'content', ['workspace_id'], unique=False)
    op.create_table('icp_profiles',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('AI_HYPOTHESIS', 'FOUNDER_CONFIRMED', 'ARCHIVED', name='icpstatus', native_enum=False, length=30), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_profiles_product_id'), 'icp_profiles', ['product_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_payload', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_credentials_integration_id'), 'integration_credentials', ['integration_id'], unique=False)
    op.create_table('investor_interactions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('DISCOVERED', 'RESEARCHING', 'SHORTLISTED', 'CONTACTED', 'REPLIED', 'MEETING', 'FOLLOW_UP', 'DUE_DILIGENCE', 'PASSED', 'INVESTED', name='investorstage', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('next_action', sa.String(length=500), nullable=False),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_interactions_investor_id'), 'investor_interactions', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investor_interactions_product_id'), 'investor_interactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_investor_interactions_workspace_id'), 'investor_interactions', ['workspace_id'], unique=False)
    op.create_table('investor_matches',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_matches_investor_id'), 'investor_matches', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investor_matches_product_id'), 'investor_matches', ['product_id'], unique=False)
    op.create_index(op.f('ix_investor_matches_workspace_id'), 'investor_matches', ['workspace_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CUSTOMER', 'INVESTOR', 'MARKETING', 'LAUNCH', 'COMMUNITY', 'CONTENT', 'PARTNERSHIP', 'MEDIA', 'EVENT', name='opportunitytype', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=False),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('reach_estimate', sa.String(length=200), nullable=False),
    sa.Column('submission_method', sa.String(length=300), nullable=False),
    sa.Column('cost', sa.String(length=200), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('promotion_rules', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_product_id'), 'opportunities', ['product_id'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_index(op.f('ix_opportunities_workspace_id'), 'opportunities', ['workspace_id'], unique=False)
    op.create_table('outreach',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PROSPECT', 'QUALIFIED', 'DRAFTED', 'APPROVED', 'SENT', 'REPLIED', 'MEETING', 'WON', 'LOST', 'NOT_NOW', name='pipelinestage', native_enum=False, length=20), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_product_id'), 'outreach', ['product_id'], unique=False)
    op.create_index(op.f('ix_outreach_target_id'), 'outreach', ['target_id'], unique=False)
    op.create_index(op.f('ix_outreach_workspace_id'), 'outreach', ['workspace_id'], unique=False)
    op.create_table('product_profiles',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_category', sa.String(length=200), nullable=False),
    sa.Column('primary_problem', sa.Text(), nullable=False),
    sa.Column('primary_buyer', sa.String(length=300), nullable=False),
    sa.Column('secondary_buyers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitive_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_ai_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_profiles_product_id'), 'product_profiles', ['product_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_workspace_id'), 'research_runs', ['workspace_id'], unique=False)
    op.create_table('action_runs',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_runs_action_id'), 'action_runs', ['action_id'], unique=False)
    op.create_table('audience_segments',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('icp_profile_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('company_size_min', sa.Integer(), nullable=True),
    sa.Column('company_size_max', sa.Integer(), nullable=True),
    sa.Column('job_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geographies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('funding_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['icp_profile_id'], ['icp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_segments_product_id'), 'audience_segments', ['product_id'], unique=False)
    op.create_table('campaign_channels',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_channels_campaign_id'), 'campaign_channels', ['campaign_id'], unique=False)
    op.create_table('campaign_metrics',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('signups', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('responses', sa.Integer(), nullable=False),
    sa.Column('meetings', sa.Integer(), nullable=False),
    sa.Column('attribution', sa.String(length=20), nullable=False),
    sa.Column('source_detail', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_metrics_campaign_id'), 'campaign_metrics', ['campaign_id'], unique=False)
    op.create_table('company_signals',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_signals_company_id'), 'company_signals', ['company_id'], unique=False)
    op.create_table('company_triggers',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('product_fit_score', sa.Float(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_triggers_company_id'), 'company_triggers', ['company_id'], unique=False)
    op.create_table('competitor_changes',
    sa.Column('competitor_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('potential_impact', sa.String(length=20), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('recommended_response', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_changes_competitor_id'), 'competitor_changes', ['competitor_id'], unique=False)
    op.create_table('contacts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('public_profile_url', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Enum('FACT', 'HYPOTHESIS', 'INFERENCE', 'UNKNOWN', name='evidencestatus', native_enum=False, length=20), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('PROSPECT', 'QUALIFIED', 'DRAFTED', 'APPROVED', 'SENT', 'REPLIED', 'MEETING', 'WON', 'LOST', 'NOT_NOW', name='pipelinestage', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False)
    op.create_table('content_variants',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'DRAFT', 'APPROVED', 'PUBLISHED', name='contentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_variants_content_id'), 'content_variants', ['content_id'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('audience_quality', sa.Float(), nullable=False),
    sa.Column('reachability', sa.Float(), nullable=False),
    sa.Column('effort', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('evidence_quality', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_scores_opportunity_id'), 'opportunity_scores', ['opportunity_id'], unique=False)
    op.create_table('opportunity_sources',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_sources_opportunity_id'), 'opportunity_sources', ['opportunity_id'], unique=False)
    op.create_table('outreach_events',
    sa.Column('outreach_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_events_outreach_id'), 'outreach_events', ['outreach_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('outreach_id', sa.Uuid(), nullable=False),
    sa.Column('draft_body', sa.Text(), nullable=False),
    sa.Column('personalization_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFTED', 'APPROVED', 'SENT', 'REJECTED', name='outreachmessagestatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_outreach_id'), 'outreach_messages', ['outreach_id'], unique=False)
    op.create_table('contact_sources',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_sources_contact_id'), 'contact_sources', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_sources_contact_id'), table_name='contact_sources')
    op.drop_table('contact_sources')
    op.drop_index(op.f('ix_outreach_messages_outreach_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_outreach_events_outreach_id'), table_name='outreach_events')
    op.drop_table('outreach_events')
    op.drop_index(op.f('ix_opportunity_sources_opportunity_id'), table_name='opportunity_sources')
    op.drop_table('opportunity_sources')
    op.drop_index(op.f('ix_opportunity_scores_opportunity_id'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_content_variants_content_id'), table_name='content_variants')
    op.drop_table('content_variants')
    op.drop_index(op.f('ix_contacts_workspace_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_competitor_changes_competitor_id'), table_name='competitor_changes')
    op.drop_table('competitor_changes')
    op.drop_index(op.f('ix_company_triggers_company_id'), table_name='company_triggers')
    op.drop_table('company_triggers')
    op.drop_index(op.f('ix_company_signals_company_id'), table_name='company_signals')
    op.drop_table('company_signals')
    op.drop_index(op.f('ix_campaign_metrics_campaign_id'), table_name='campaign_metrics')
    op.drop_table('campaign_metrics')
    op.drop_index(op.f('ix_campaign_channels_campaign_id'), table_name='campaign_channels')
    op.drop_table('campaign_channels')
    op.drop_index(op.f('ix_audience_segments_product_id'), table_name='audience_segments')
    op.drop_table('audience_segments')
    op.drop_index(op.f('ix_action_runs_action_id'), table_name='action_runs')
    op.drop_table('action_runs')
    op.drop_index(op.f('ix_research_runs_workspace_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_product_profiles_product_id'), table_name='product_profiles')
    op.drop_table('product_profiles')
    op.drop_index(op.f('ix_outreach_workspace_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_target_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_product_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_opportunities_workspace_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_product_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_investor_matches_workspace_id'), table_name='investor_matches')
    op.drop_index(op.f('ix_investor_matches_product_id'), table_name='investor_matches')
    op.drop_index(op.f('ix_investor_matches_investor_id'), table_name='investor_matches')
    op.drop_table('investor_matches')
    op.drop_index(op.f('ix_investor_interactions_workspace_id'), table_name='investor_interactions')
    op.drop_index(op.f('ix_investor_interactions_product_id'), table_name='investor_interactions')
    op.drop_index(op.f('ix_investor_interactions_investor_id'), table_name='investor_interactions')
    op.drop_table('investor_interactions')
    op.drop_index(op.f('ix_integration_credentials_integration_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_icp_profiles_product_id'), table_name='icp_profiles')
    op.drop_table('icp_profiles')
    op.drop_index(op.f('ix_content_workspace_id'), table_name='content')
    op.drop_index(op.f('ix_content_product_id'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_competitors_workspace_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_product_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_companies_workspace_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_product_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_product_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brand_mentions_workspace_id'), table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_product_id'), table_name='brand_mentions')
    op.drop_table('brand_mentions')
    op.drop_index(op.f('ix_brand_brain_workspace_id'), table_name='brand_brain')
    op.drop_table('brand_brain')
    op.drop_index(op.f('ix_actions_workspace_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_product_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_research_sources_workspace_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_products_workspace_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_evidence_workspace_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_runs_workspace_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_table('workspaces')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('investors')
    # ### end Alembic commands ###
