"""video_brand_kit_product_screenshot

Revision ID: 6b28d71118dc
Revises: 786be1045adb
Create Date: 2026-08-28 20:01:13.586722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b28d71118dc'
down_revision: Union[str, None] = '786be1045adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_brand_kits', sa.Column('product_screenshot_url', sa.String(length=500), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_brand_kits', 'product_screenshot_url')
    # ### end Alembic commands ###
