"""daily_content_promotion_engine

Revision ID: 786be1045adb
Revises: 94de3e04c111
Create Date: 2026-08-28 17:39:54.132625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '786be1045adb'
down_revision: Union[str, None] = '94de3e04c111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('content_variant_id', sa.Uuid(), nullable=True),
    sa.Column('script', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('has_voiceover', sa.Boolean(), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('SCRIPT_READY', 'RENDERING', 'READY', 'FAILED', name='videostatus', native_enum=False, length=20), nullable=False),
    sa.Column('render_log', sa.Text(), nullable=False),
    sa.Column('brand_kit_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_variant_id'], ['content_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_product_id'), 'videos', ['product_id'], unique=False)
    op.create_index(op.f('ix_videos_workspace_id'), 'videos', ['workspace_id'], unique=False)
    op.create_table('video_brand_kits',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('background_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('font_family', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_brand_kits_product_id'), 'video_brand_kits', ['product_id'], unique=False)
    op.create_index(op.f('ix_video_brand_kits_workspace_id'), 'video_brand_kits', ['workspace_id'], unique=False)
    # server_default values below are required because these tables already
    # have live rows (demo + real data from the three prior passes) — a
    # bare NOT NULL add_column would fail against the existing rows.
    op.add_column('content', sa.Column('content_type', sa.String(length=30), nullable=False, server_default='educational'))
    op.add_column('content', sa.Column('origin', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('content', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'content', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.add_column('content_variants', sa.Column('platform_format', sa.String(length=30), nullable=False, server_default='post'))
    op.add_column('content_variants', sa.Column('cta', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('content_variants', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('content_variants', sa.Column('rejected_reason', sa.Text(), nullable=False, server_default=''))
    op.add_column('content_variants', sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.add_column('content_variants', sa.Column('video_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'content_variants', 'videos', ['video_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_variants', type_='foreignkey')
    op.drop_column('content_variants', 'video_id')
    op.drop_column('content_variants', 'quality_flags')
    op.drop_column('content_variants', 'rejected_reason')
    op.drop_column('content_variants', 'scheduled_at')
    op.drop_column('content_variants', 'cta')
    op.drop_column('content_variants', 'platform_format')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'campaign_id')
    op.drop_column('content', 'origin')
    op.drop_column('content', 'content_type')
    op.drop_index(op.f('ix_video_brand_kits_workspace_id'), table_name='video_brand_kits')
    op.drop_index(op.f('ix_video_brand_kits_product_id'), table_name='video_brand_kits')
    op.drop_table('video_brand_kits')
    op.drop_index(op.f('ix_videos_workspace_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_product_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
