"""autonomous growth engine

Revision ID: 94de3e04c111
Revises: a2095f2f0311
Create Date: 2026-08-28 10:43:25.101878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94de3e04c111'
down_revision: Union[str, None] = 'a2095f2f0311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_insights',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IGNORED', name='learninginsightstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_insights_product_id'), 'learning_insights', ['product_id'], unique=False)
    op.create_index(op.f('ix_learning_insights_workspace_id'), 'learning_insights', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_insights_workspace_id'), table_name='learning_insights')
    op.drop_index(op.f('ix_learning_insights_product_id'), table_name='learning_insights')
    op.drop_table('learning_insights')
    # ### end Alembic commands ###
