"""visibility module

Revision ID: a2095f2f0311
Revises: 2db789a1eb66
Create Date: 2026-08-28 09:43:18.215156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2095f2f0311'
down_revision: Union[str, None] = '2db789a1eb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_truth',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('target_customer', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('core_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('approved_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forbidden_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=False),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing', sa.Text(), nullable=False),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_truth_product_id'), 'product_truth', ['product_id'], unique=True)
    op.create_table('websites',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('repository_owner', sa.String(length=200), nullable=False),
    sa.Column('repository_name', sa.String(length=200), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('deployment_platform', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('framework_confidence', sa.Enum('VERIFIED', 'ESTIMATED', 'UNKNOWN', name='confidencelabel', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_product_id'), 'websites', ['product_id'], unique=False)
    op.create_index(op.f('ix_websites_workspace_id'), 'websites', ['workspace_id'], unique=False)
    op.create_table('design_constitution',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('typography', sa.Text(), nullable=False),
    sa.Column('colors', sa.Text(), nullable=False),
    sa.Column('logo_rules', sa.Text(), nullable=False),
    sa.Column('spacing', sa.Text(), nullable=False),
    sa.Column('component_system', sa.Text(), nullable=False),
    sa.Column('navigation', sa.Text(), nullable=False),
    sa.Column('layout', sa.Text(), nullable=False),
    sa.Column('animation', sa.Text(), nullable=False),
    sa.Column('responsive_rules', sa.Text(), nullable=False),
    sa.Column('glassmorphism_rules', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_constitution_website_id'), 'design_constitution', ['website_id'], unique=True)
    op.create_table('protected_paths',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('path_pattern', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protected_paths_website_id'), 'protected_paths', ['website_id'], unique=False)
    op.create_table('visibility_questions',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('coverage_status', sa.Enum('MENTIONED', 'NOT_DETECTED', name='visibilitycoveragestatus', native_enum=False, length=20), nullable=False),
    sa.Column('evidence_snippet', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_questions_website_id'), 'visibility_questions', ['website_id'], unique=False)
    op.create_table('website_guardrails',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('protect_product_meaning', sa.Boolean(), nullable=False),
    sa.Column('protect_brand_voice', sa.Boolean(), nullable=False),
    sa.Column('protect_visual_design', sa.Boolean(), nullable=False),
    sa.Column('require_approval_content', sa.Boolean(), nullable=False),
    sa.Column('require_approval_code', sa.Boolean(), nullable=False),
    sa.Column('require_approval_production', sa.Boolean(), nullable=False),
    sa.Column('block_unsupported_claims', sa.Boolean(), nullable=False),
    sa.Column('run_build_checks', sa.Boolean(), nullable=False),
    sa.Column('run_visual_checks', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_guardrails_website_id'), 'website_guardrails', ['website_id'], unique=True)
    op.create_table('website_opportunities',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_path', sa.String(length=500), nullable=False),
    sa.Column('current_coverage', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='opportunitycoverage', native_enum=False, length=20), nullable=False),
    sa.Column('product_fit_score', sa.Float(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROPOSED', 'REJECTED', 'COMPLETED', name='websiteopportunitystatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_opportunities_website_id'), 'website_opportunities', ['website_id'], unique=False)
    op.create_table('website_scans',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_scans_website_id'), 'website_scans', ['website_id'], unique=False)
    op.create_table('seo_issues',
    sa.Column('website_scan_id', sa.Uuid(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['website_scan_id'], ['website_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_issues_website_scan_id'), 'seo_issues', ['website_scan_id'], unique=False)
    op.create_table('website_changes',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('website_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=20), nullable=False),
    sa.Column('mode', sa.Enum('ANALYZE_ONLY', 'PROPOSE', 'PREPARE', 'AUTONOMOUS', name='optimizationmode', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFTED', 'VALIDATED', 'BLOCKED', 'APPROVED', 'BRANCH_CREATED', 'PR_CREATED', 'MERGED', 'REJECTED', name='websitechangestatus', native_enum=False, length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=300), nullable=False),
    sa.Column('base_branch', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=100), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=500), nullable=False),
    sa.Column('files_changed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_opportunity_id'], ['website_opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_changes_website_id'), 'website_changes', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_changes_website_id'), table_name='website_changes')
    op.drop_table('website_changes')
    op.drop_index(op.f('ix_seo_issues_website_scan_id'), table_name='seo_issues')
    op.drop_table('seo_issues')
    op.drop_index(op.f('ix_website_scans_website_id'), table_name='website_scans')
    op.drop_table('website_scans')
    op.drop_index(op.f('ix_website_opportunities_website_id'), table_name='website_opportunities')
    op.drop_table('website_opportunities')
    op.drop_index(op.f('ix_website_guardrails_website_id'), table_name='website_guardrails')
    op.drop_table('website_guardrails')
    op.drop_index(op.f('ix_visibility_questions_website_id'), table_name='visibility_questions')
    op.drop_table('visibility_questions')
    op.drop_index(op.f('ix_protected_paths_website_id'), table_name='protected_paths')
    op.drop_table('protected_paths')
    op.drop_index(op.f('ix_design_constitution_website_id'), table_name='design_constitution')
    op.drop_table('design_constitution')
    op.drop_index(op.f('ix_websites_workspace_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_product_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_product_truth_product_id'), table_name='product_truth')
    op.drop_table('product_truth')
    # ### end Alembic commands ###
